[features]
seeds = false
[programs.localnet]
splendor = "xmtn2vByiRMraod2aVHYXB9mxRJQ3Z3Y7SnvSdAy8qn"

[registry]
url = "https://anchor.projectserum.com"

[[test.validator.clone]]
address = "4bcFeLv4nydFrsZqV5CgwCVrPhkQKsXtzfy2KyMz7ozM"
[[test.validator.clone]]
address = "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"
[[test.validator.clone]]
address = "Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB"
[[test.validator.clone]]
address = "Amig8TisuLpzun8XyGfC5HJHHGUQEscjLgoTWsCCKihg"
[[test.validator.clone]]
address = "gLhY2arqFpmVGkpbBbTi3TeWbsWevA8dqrwbKacK3vJ"
[[test.validator.clone]]
address = "VMc13PVs9GBhL1hxXeF33XtaKVMjg8YyMMszGawFPS2"
[[test.validator.clone]]
address = "936Ae3riWbnC5KbvsnkBnJ6F7wjHUNNk2SMNEMvPwiyp"
[[test.validator.clone]]
address = "BJb1uP68pEuvRojzM61JR49pNSodihorVk6TosVMsr74"
[test.validator]
url = "m"

[provider]
cluster = "localnet"
wallet = "devlet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
